### ISSUE TITLE
Can't use method return value in write context error

### ISSUE THREAD

**Issue by katalysis** [concrete5-community-store/community_store_shipping_tablerate#1]
Trying to add a Table Rate method shipping in /dashboard/store/settings/shipping results in an error:

An unexpected error occurred.
Can't use method return value in write context

**Comment by Jozzeh** [comment]
Can you give some more information about your setup?   
- concrete5 version
- PHP version  

I've tested the package on a clean install of both the latest version of Concrete5 and community store... No error though

**Comment by katalysis** [comment]
concrete5 environment is attached.

[environment.txt](https://github.com/concrete5-community-store/community_store_shipping_tablerate/files/505754/environment.txt)

Additionally here it the php error generated in the server log:

2016-10-03 08:10:55 Error 

.278 [NOTICE] [92.19.224.112:60368] [STDERR] PHP Fatal error: Can't use method return value in write context in /var/www/vhosts/dev5.katalysis.net/httpdocs/packages/community_store_shipping_tablerate/elements/shipping_method_types/tablerate/dashboard_form.php on line 30

**Comment by Jozzeh** [comment]
Thanks, with this information, I think i've solved the issue. 
I've updated the /elements/shipping_method_types/tablerate/dashboard_form.php  
Please update that file and check if the error is gone.

**Comment by katalysis** [comment]
That's fixed it. 

Many thanks.
