### ISSUE TITLE
csv upload - HTTP request failed

### ISSUE THREAD

**Issue by katalysis** [concrete5-community-store/community_store_shipping_tablerate#5]
This seams to have stopped working with the latest Community Store.  Trying to upload a csv file returns the error:

`file(https://dev24.katalysis.net/application/files/5416/2617/4048/Tablerates-main-2018.csv): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized`

![screenshot-dev24 katalysis net-2021 07 13-12_03_30](https://user-images.githubusercontent.com/4235012/125441494-fd374b37-c23d-4c90-b705-fb607f6f3720.png)

**Comment by mnakalay** [comment]
@Mesuva this was due to a server setting, the installation folder was htaccess password protected. You can close.
